import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { badRequest } from './httpError.js';
import { uploadsDir } from './store.js';

export const allowedMimeTypes = {
  'image/jpeg': 'jpg',
  'image/png': 'png',
  'image/webp': 'webp',
  'application/pdf': 'pdf',
};

export const maxUploadBytes = 3 * 1024 * 1024;

// Without persistence (tests) files are kept in memory instead of on disk.
const memoryFiles = new Map();

// Checks the leading bytes so a file can't claim to be an image while containing something else.
function matchesSignature(buffer, mimeType) {
  const signatures = {
    'image/jpeg': [0xff, 0xd8, 0xff],
    'image/png': [0x89, 0x50, 0x4e, 0x47],
    'image/webp': [0x52, 0x49, 0x46, 0x46],
    'application/pdf': [0x25, 0x50, 0x44, 0x46],
  };
  return signatures[mimeType].every((byte, index) => buffer[index] === byte);
}

export function saveUpload({ mimeType, dataBase64 }) {
  if (typeof mimeType !== 'string' || !Object.hasOwn(allowedMimeTypes, mimeType)) {
    throw badRequest('INVALID_FILE_TYPE', 'Upload a JPG, PNG, WEBP or PDF file.');
  }

  const buffer = Buffer.from(typeof dataBase64 === 'string' ? dataBase64 : '', 'base64');
  if (buffer.length === 0) throw badRequest('EMPTY_FILE', 'The file is empty.');
  if (buffer.length > maxUploadBytes) throw badRequest('FILE_TOO_LARGE', 'Files must be 3 MB or smaller.');
  if (!matchesSignature(buffer, mimeType)) throw badRequest('INVALID_FILE', 'The file content does not match its type.');

  const fileId = `${crypto.randomUUID()}.${allowedMimeTypes[mimeType]}`;
  const directory = uploadsDir();
  if (directory) {
    fs.mkdirSync(directory, { recursive: true, mode: 0o700 });
    fs.writeFileSync(path.join(directory, fileId), buffer, { mode: 0o600 });
  } else {
    memoryFiles.set(fileId, buffer);
  }
  return fileId;
}

export function readUpload(fileId) {
  // File ids are generated by saveUpload; reject anything else so paths can't escape the folder.
  if (!/^[0-9a-f-]{36}\.(jpg|png|webp|pdf)$/.test(fileId)) return null;

  const directory = uploadsDir();
  if (!directory) return memoryFiles.get(fileId) ?? null;

  const filePath = path.join(directory, fileId);
  return fs.existsSync(filePath) ? fs.readFileSync(filePath) : null;
}

export function deleteUpload(fileId) {
  if (!fileId || !/^[0-9a-f-]{36}\.(jpg|png|webp|pdf)$/.test(fileId)) return;
  const directory = uploadsDir();
  if (!directory) {
    memoryFiles.delete(fileId);
    return;
  }
  fs.rmSync(path.join(directory, fileId), { force: true });
}
